apiVersion: v1
name: aws-gateway-controller-chart
description: A Helm chart for the Gateway Controller for AWS VPC Lattice
version: v1.0.6
appVersion: v1.0.6
home: https://github.com/aws/aws-application-networking-k8s
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws/aws-application-networking-k8s
maintainers:
  - name: AWS Application Networking Kubernetes project admins
    url: https://github.com/orgs/aws/teams/aws-application-networking-maintainer
keywords:
  - aws
  - kubernetes
  - gateway-api
  - vpc-lattice
