# Default values for aws-application-networking-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: public.ecr.aws/aws-application-networking-k8s/aws-gateway-controller
  tag: v1.0.6
  pullPolicy: IfNotPresent
  pullSecrets: []

nameOverride: ""
fullnameOverride: ""

deployment:
  annotations:
    kubectl.kubernetes.io/default-container: manager
  labels:
    control-plane: gateway-api-controller
  containerPort: 8080
  # Which nodeSelector to set?
  # See: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
  nodeSelector:
    kubernetes.io/os: linux
  # Which tolerations to set?
  # See: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
  tolerations: []
  # What affinity to set?
  # See: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}
  # Which priorityClassName to set?
  # See: https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#pod-priority
  priorityClassName: ""
  # Number of replicas.
  replicas: 2

# If "installScope: cluster" then these labels will be applied to ClusterRole
role:
 labels: {}

metrics:
  service:
    # Set to true to automatically create a Kubernetes Service resource for the
    # Prometheus metrics server endpoint in controller
    create: false
    # Which Type to use for the Kubernetes Service?
    # See: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
    type: "ClusterIP"

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

# log level for the controller
log:
  level: info

# Set to "namespace" to install the controller in a namespaced scope, will only
# watch for object creation in the namespace. By default installScope is
# cluster wide.
installScope: cluster

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  name: gateway-api-controller
  annotations: {}
    # eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME

awsRegion:
awsAccountId:
clusterVpcId:
clusterName:
defaultServiceNetwork:
latticeEndpoint:
webhookEnabled: true

# TLS cert/key for the webhook. If specified, values must be base64 encoded
webhookTLS:
  caCert:
  cert:
  key: